### ISSUE TITLE
C006.heic is invalid

### ISSUE THREAD

**Issue by silviu22** [nokiatech/heif_conformance#5]
[C006-corrected.zip](https://github.com/nokiatech/heif_conformance/files/6091481/C006-corrected.zip)
The image data for the C006 primary item (0x03ED) is incorrect (too short). This file is supposed to have an alpha plane mask, but contains only 10 bytes (only a 6-byte SEI nal unit). conformance_file_descriptions.xlsx file specifies that the bitstream for C006.heic is supposed to contain data from B001 and B006. 

B006.265 is correct, because it has the 6 bytes of SEI followed by 291 bytes of image data. The data inside C006,heic is truncated.

I attached what I believe is contains the missing data corrected file.

The other problem with C006.heic is that the primary item (0x03ED) is hidden (has flags = 1 in its 'infe' box). This breaks the rule from ISO/IEC 230008-12:2017 that says on page 8 clause 6.4.2 (Hidden images): "The primary item shall not be a hidden image item".

**Comment by lassehe** [comment]
Thank you for reporting these issues.

Exactly as described, unintentionally the SEI message only was inserted as the item data. This affected also C052.heic which uses the same input bitstream B006.265.

The hidden primary item issue was fixed by setting the master image as the primary item, as it is not recommended having auxiliary image as the primary item.

Regenerated files submitted in commit 795f55f have these issues fixed.
