### ISSUE TITLE
'iinf' version 2 is not a valid version

### ISSUE THREAD

**Issue by leo-barnes** [nokiatech/heif_conformance#7]
The following files are specifying the 'iinf' box as having version 2, which is not valid according to ISOBMFF (only version 0 and 1 are defined):
- multilayer001.heic
- multilayer002.heic
- multilayer004.heic
- multilayer005.heic

Going by the git history, some other files (C008.heic for example) used to also have iinf version 2, but then got changed in a commit mentioning they got re-written (`"Most files are now written by using HEIF writer v3.1"`), so this is potentially an issue with the pre v3.1 HEIF writer.

**Comment by lassehe** [comment]
Thank you for reporting this. That is right. These files are using version 1 syntax, but because of a bug version was written as 2. The issue was in several other files too, but it got fixed earlier during the update mentioned. These multi-layer files were generated a bit differently, and apparently I did not realize to update these at the time.
